language: ruby
sudo: false

env:
  - PUPPET_VERSION=4.2.2
  - PUPPET_VERSION=4.2.1
  - PUPPET_VERSION=4.2.0
  - PUPPET_VERSION=4.1.0
  - PUPPET_VERSION=4.0.0
  - PUPPET_VERSION=3.8.2
  - PUPPET_VERSION=3.8.1
  - PUPPET_VERSION=3.7.5
  - PUPPET_VERSION=3.7.4
  - PUPPET_VERSION=3.7.3
  - PUPPET_VERSION=3.7.2
  - PUPPET_VERSION=3.7.1
  - PUPPET_VERSION=3.7.0
  - PUPPET_VERSION=3.6.2
  - PUPPET_VERSION=3.6.1
  - PUPPET_VERSION=3.6.0

addons:
  apt:
    packages:
      - apache2

rvm:
  - 2.2.3
  - 2.2.2
  - 2.2.1
  - 2.2.0
  - 2.1.0
  - 2.0.0
  - 1.9.3

script:
# Download the build artifact
  - 'curl "https://github.com/jolshevski/chester/releases/download/1.0.0/linux_amd64" -o subject'

# Download modules
  - 'mkdir -p data/v3/files'
  - 'curl "https://forgeapi.puppetlabs.com/v3/files/puppetlabs-stdlib-4.9.0.tar.gz" -o "data/v3/files/puppetlabs-stdlib-4.9.0.tar.gz"'
  - 'curl "https://forgeapi.puppetlabs.com/v3/files/puppetlabs-apache-1.6.0.tar.gz" -o "data/v3/files/puppetlabs-apache-1.6.0.tar.gz"'
  - 'curl "https://forgeapi.puppetlabs.com/v3/files/puppetlabs-apache-1.5.0.tar.gz" -o "data/v3/files/puppetlabs-apache-1.5.0.tar.gz"'
  - 'curl "https://forgeapi.puppetlabs.com/v3/files/puppetlabs-concat-1.2.4.tar.gz" -o "data/v3/files/puppetlabs-concat-1.2.4.tar.gz"'

# Start chester and apache
  - 'subject -modulepath modules &'
  - 'apache2 -d ./ -DFOREGROUND'

# Attempt to install the module
  - 'puppet module install puppetlabs-apache --module_repository http://localhost:8081 --trace'
